site:
  name: מכון טון - ToneClinic
  # TODO: add official site url
  site: 'https://toneclinic.net'
  base: '/'
  trailingSlash: false
  # TODO: add google site verification id
  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: מכון טון
    template: '%s — מכון טון'
  description: 'מרפאת שמיעה מקצועית - שירותי אודיולוגיה מתקדמים וטיפול בשמיעה.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: מכון טון
    images:
      - url: '~/assets/images/default.jpg'
        width: 1200
        height: 628
    type: website
  twitter:
    # TODO: add twitter handle and site
    handle: '@toneclinic'
    site: '@toneclinic'
    cardType: summary_large_image

i18n:
  language: he
  textDirection: rtl

analytics:
  vendors:
    googleAnalytics:
      # TODO: add google analytics id
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
